name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Publish-Website:
    name: Publish-Website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Update to use v2 for better performance and stability

      - name: Upload the artifact
        uses: actions/upload-artifact@v4  # This is correct, v4 is the latest version as of now
        with:
          name: wpcom  # The artifact name to be uploaded
          path: |
            .  # Upload all files in the current directory
            !.git*  # Exclude .git directory and files
